version: "3"

volumes:
  production_postgres_data: {}

services:
  rgi:
    build:
      context: .
      dockerfile: Dockerfile
    image: rgi
    container_name: rgi
    env_file:
      - ./.envs/.production/.dash
    expose:
    - 80
    restart: always
    networks:
    - caddy_network

networks:
  caddy_network:
    external:
      name: docker_caddy_network
