version: "3"

services:
  rgi:
    build:
      context: .
      dockerfile: Dockerfile
    image: rgi
    container_name: rgi
    env_file:
      - .envs/.production/.env
    expose:
    - 80
    restart: always
